[2025-02-03 22:19:29,531] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2025-02-03 22:19:29,535] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2025-02-03 22:19:29,535] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-02-03 22:19:29,535] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2025-02-03 22:19:29,535] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-02-03 22:19:29,551] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2024-10-14 00:00:00+00:00
[2025-02-03 22:19:29,555] {standard_task_runner.py:52} INFO - Started process 40996 to run task
[2025-02-03 22:19:29,559] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2024-10-14T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmptrw0gn_8', '--error-file', '/tmp/tmp80q73fmd']
[2025-02-03 22:19:29,560] {standard_task_runner.py:80} INFO - Job 44: Subtask extrai_dados
[2025-02-03 22:19:29,596] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-10-14T00:00:00+00:00 [running]> on host luan-capella
[2025-02-03 22:19:29,639] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2024-10-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-14T00:00:00+00:00
[2025-02-03 22:19:30,896] {python.py:173} INFO - Done. Returned value was: None
[2025-02-03 22:19:30,909] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20241014T000000, start_date=20250204T011929, end_date=20250204T011930
[2025-02-03 22:19:30,934] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-03 22:19:30,967] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
