[2025-02-03 22:20:22,163] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-12-30T00:00:00+00:00 [queued]>
[2025-02-03 22:20:22,167] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-12-30T00:00:00+00:00 [queued]>
[2025-02-03 22:20:22,167] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-02-03 22:20:22,167] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2025-02-03 22:20:22,168] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-02-03 22:20:22,187] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2024-12-30 00:00:00+00:00
[2025-02-03 22:20:22,192] {standard_task_runner.py:52} INFO - Started process 42114 to run task
[2025-02-03 22:20:22,195] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2024-12-30T00:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpdw4peosy', '--error-file', '/tmp/tmp69seffgt']
[2025-02-03 22:20:22,195] {standard_task_runner.py:80} INFO - Job 68: Subtask extrai_dados
[2025-02-03 22:20:22,226] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-12-30T00:00:00+00:00 [running]> on host luan-capella
[2025-02-03 22:20:22,267] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2024-12-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-30T00:00:00+00:00
[2025-02-03 22:20:23,138] {python.py:173} INFO - Done. Returned value was: None
[2025-02-03 22:20:23,146] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20241230T000000, start_date=20250204T012022, end_date=20250204T012023
[2025-02-03 22:20:23,209] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-03 22:20:23,222] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
