[2025-02-03 22:20:29,340] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-02-03 22:20:29,344] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-02-03 22:20:29,344] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-02-03 22:20:29,344] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2025-02-03 22:20:29,344] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-02-03 22:20:29,358] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2025-01-06 00:00:00+00:00
[2025-02-03 22:20:29,364] {standard_task_runner.py:52} INFO - Started process 42263 to run task
[2025-02-03 22:20:29,367] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2025-01-06T00:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpw72dhn0f', '--error-file', '/tmp/tmp_h7z_wfk']
[2025-02-03 22:20:29,368] {standard_task_runner.py:80} INFO - Job 71: Subtask extrai_dados
[2025-02-03 22:20:29,403] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2025-01-06T00:00:00+00:00 [running]> on host luan-capella
[2025-02-03 22:20:29,451] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2025-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-01-06T00:00:00+00:00
[2025-02-03 22:20:30,354] {python.py:173} INFO - Done. Returned value was: None
[2025-02-03 22:20:30,368] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20250106T000000, start_date=20250204T012029, end_date=20250204T012030
[2025-02-03 22:20:30,421] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-03 22:20:30,433] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
