[2025-02-03 22:19:35,599] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2025-02-03 22:19:35,603] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2025-02-03 22:19:35,603] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-02-03 22:19:35,603] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2025-02-03 22:19:35,603] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-02-03 22:19:35,617] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2024-10-21 00:00:00+00:00
[2025-02-03 22:19:35,622] {standard_task_runner.py:52} INFO - Started process 41123 to run task
[2025-02-03 22:19:35,624] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpwi5i_f_o', '--error-file', '/tmp/tmp41xabpr0']
[2025-02-03 22:19:35,625] {standard_task_runner.py:80} INFO - Job 47: Subtask extrai_dados
[2025-02-03 22:19:35,661] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-10-21T00:00:00+00:00 [running]> on host luan-capella
[2025-02-03 22:19:35,741] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2024-10-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-21T00:00:00+00:00
[2025-02-03 22:19:36,438] {python.py:173} INFO - Done. Returned value was: None
[2025-02-03 22:19:36,451] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20241021T000000, start_date=20250204T011935, end_date=20250204T011936
[2025-02-03 22:19:36,518] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-03 22:19:36,538] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
