[2025-02-03 22:19:54,101] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-11-18T00:00:00+00:00 [queued]>
[2025-02-03 22:19:54,105] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-11-18T00:00:00+00:00 [queued]>
[2025-02-03 22:19:54,105] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-02-03 22:19:54,105] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2025-02-03 22:19:54,105] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-02-03 22:19:54,123] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2024-11-18 00:00:00+00:00
[2025-02-03 22:19:54,127] {standard_task_runner.py:52} INFO - Started process 41543 to run task
[2025-02-03 22:19:54,131] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2024-11-18T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpno0qh66v', '--error-file', '/tmp/tmpmtfr_tox']
[2025-02-03 22:19:54,131] {standard_task_runner.py:80} INFO - Job 56: Subtask extrai_dados
[2025-02-03 22:19:54,166] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2024-11-18T00:00:00+00:00 [running]> on host luan-capella
[2025-02-03 22:19:54,209] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2024-11-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-11-18T00:00:00+00:00
[2025-02-03 22:19:55,237] {python.py:173} INFO - Done. Returned value was: None
[2025-02-03 22:19:55,249] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20241118T000000, start_date=20250204T011954, end_date=20250204T011955
[2025-02-03 22:19:55,304] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-03 22:19:55,333] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
